"""Initial cricket storage schema

Revision ID: 0001_initial
Revises:
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conversations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conversations")),
    )
    op.create_index(op.f("ix_conversations_owner_id"), "conversations", ["owner_id"], unique=False)
    op.create_table(
        "source_imports",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("dataset_url", sa.Text(), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.Column("selection_key", sa.String(length=64), nullable=False),
        sa.Column("source_revision", sa.Text(), nullable=False),
        sa.Column("downloaded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("imported_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("date_start", sa.Date(), nullable=True),
        sa.Column("date_end", sa.Date(), nullable=True),
        sa.Column("counts", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_imports")),
        sa.UniqueConstraint(
            "provider", "checksum", "selection_key", name=op.f("uq_source_imports_provider")
        ),
    )
    op.create_table(
        "matches",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("format", sa.String(length=8), nullable=False),
        sa.Column("date_start", sa.Date(), nullable=False),
        sa.Column("date_end", sa.Date(), nullable=False),
        sa.Column("teams", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("venue", sa.Text(), nullable=True),
        sa.Column("balls_per_over", sa.Integer(), nullable=False),
        sa.Column("source_import_id", sa.Uuid(), nullable=False),
        sa.Column("source_checksum", sa.String(length=64), nullable=False),
        sa.Column("source_revision", sa.Integer(), nullable=False),
        sa.Column("data_version", sa.String(length=16), nullable=False),
        sa.Column("missing", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("info", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.CheckConstraint("format IN ('odi','t20i')", name=op.f("ck_matches_format")),
        sa.CheckConstraint("balls_per_over > 0", name=op.f("ck_matches_balls_per_over")),
        sa.ForeignKeyConstraint(
            ["source_import_id"],
            ["source_imports.id"],
            name=op.f("fk_matches_source_import_id_source_imports"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_matches")),
    )
    op.create_index(op.f("ix_matches_date_start"), "matches", ["date_start"], unique=False)
    op.create_index(op.f("ix_matches_format"), "matches", ["format"], unique=False)
    op.create_table(
        "messages",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("turn_number", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "role IN ('system','user','assistant','tool','summary')", name=op.f("ck_messages_role")
        ),
        sa.CheckConstraint(
            "ordinal >= 0 AND turn_number >= 0", name=op.f("ck_messages_positive_order")
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_messages_conversation_id_conversations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_messages")),
        sa.UniqueConstraint("conversation_id", "ordinal", name=op.f("uq_messages_conversation_id")),
        sa.UniqueConstraint("id", "conversation_id", name=op.f("uq_messages_id")),
    )
    op.create_index(
        op.f("ix_messages_conversation_id"), "messages", ["conversation_id"], unique=False
    )
    op.create_table(
        "players",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("unique_name", sa.String(length=255), nullable=False),
        sa.Column("aliases", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("register_import_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["register_import_id"],
            ["source_imports.id"],
            name=op.f("fk_players_register_import_id_source_imports"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_players")),
    )
    op.create_index(op.f("ix_players_name"), "players", ["name"], unique=False)
    op.create_table(
        "datasets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("player_id", sa.String(length=36), nullable=True),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("provenance", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("coverage", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_datasets_conversation_id_conversations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["player_id"], ["players.id"], name=op.f("fk_datasets_player_id_players")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_datasets")),
        sa.UniqueConstraint("id", "conversation_id", name=op.f("uq_datasets_id")),
    )
    op.create_index(
        op.f("ix_datasets_conversation_id"), "datasets", ["conversation_id"], unique=False
    )
    op.create_table(
        "external_player_ids",
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("external_id", sa.String(length=100), nullable=False),
        sa.Column("player_id", sa.String(length=36), nullable=False),
        sa.Column("source_import_id", sa.Uuid(), nullable=False),
        sa.Column("profile", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("profile_retrieved_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["player_id"], ["players.id"], name=op.f("fk_external_player_ids_player_id_players")
        ),
        sa.ForeignKeyConstraint(
            ["source_import_id"],
            ["source_imports.id"],
            name=op.f("fk_external_player_ids_source_import_id_source_imports"),
        ),
        sa.PrimaryKeyConstraint("provider", "external_id", name=op.f("pk_external_player_ids")),
        sa.UniqueConstraint(
            "player_id", "provider", "external_id", name=op.f("uq_external_player_ids_player_id")
        ),
    )
    op.create_index(
        op.f("ix_external_player_ids_player_id"), "external_player_ids", ["player_id"], unique=False
    )
    op.create_table(
        "innings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("match_id", sa.String(length=64), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("team", sa.String(length=255), nullable=False),
        sa.Column("super_over", sa.Boolean(), nullable=False),
        sa.Column("data_complete", sa.Boolean(), nullable=False),
        sa.Column("missing", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("penalty_pre", sa.Integer(), nullable=False),
        sa.Column("penalty_post", sa.Integer(), nullable=False),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.CheckConstraint("number > 0", name=op.f("ck_innings_number")),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["matches.id"],
            name=op.f("fk_innings_match_id_matches"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_innings")),
        sa.UniqueConstraint("match_id", "number", name=op.f("uq_innings_match_id")),
    )
    op.create_index(op.f("ix_innings_match_id"), "innings", ["match_id"], unique=False)
    op.create_table(
        "match_players",
        sa.Column("match_id", sa.String(length=64), nullable=False),
        sa.Column("player_id", sa.String(length=36), nullable=False),
        sa.Column("team", sa.String(length=255), nullable=False),
        sa.Column("source_name", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["matches.id"],
            name=op.f("fk_match_players_match_id_matches"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["player_id"], ["players.id"], name=op.f("fk_match_players_player_id_players")
        ),
        sa.PrimaryKeyConstraint("match_id", "player_id", name=op.f("pk_match_players")),
    )
    op.create_table(
        "tool_calls",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("request_message_id", sa.Uuid(), nullable=False),
        sa.Column("result_message_id", sa.Uuid(), nullable=True),
        sa.Column("model_call_id", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("args", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_tool_calls_conversation_id_conversations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["request_message_id", "conversation_id"],
            ["messages.id", "messages.conversation_id"],
            name=op.f("fk_tool_calls_request_message_id_messages"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["result_message_id", "conversation_id"],
            ["messages.id", "messages.conversation_id"],
            name=op.f("fk_tool_calls_result_message_id_messages"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tool_calls")),
        sa.UniqueConstraint(
            "conversation_id", "model_call_id", name=op.f("uq_tool_calls_conversation_id")
        ),
    )
    op.create_index(
        op.f("ix_tool_calls_conversation_id"), "tool_calls", ["conversation_id"], unique=False
    )
    op.create_table(
        "chart_specs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("dataset_id", sa.Uuid(), nullable=False),
        sa.Column("spec", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_chart_specs_conversation_id_conversations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["dataset_id", "conversation_id"],
            ["datasets.id", "datasets.conversation_id"],
            name=op.f("fk_chart_specs_dataset_id_datasets"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chart_specs")),
    )
    op.create_index(
        op.f("ix_chart_specs_conversation_id"), "chart_specs", ["conversation_id"], unique=False
    )
    op.create_table(
        "deliveries",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("innings_id", sa.Uuid(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("over_number", sa.Integer(), nullable=False),
        sa.Column("delivery_number", sa.Integer(), nullable=False),
        sa.Column("legal_index", sa.Integer(), nullable=True),
        sa.Column("batter_id", sa.String(length=36), nullable=True),
        sa.Column("non_striker_id", sa.String(length=36), nullable=True),
        sa.Column("bowler_id", sa.String(length=36), nullable=True),
        sa.Column("batter_runs", sa.Integer(), nullable=True),
        sa.Column("extras_runs", sa.Integer(), nullable=True),
        sa.Column("total_runs", sa.Integer(), nullable=True),
        sa.Column("extras", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_legal", sa.Boolean(), nullable=True),
        sa.Column("is_boundary", sa.Boolean(), nullable=True),
        sa.Column("data_complete", sa.Boolean(), nullable=False),
        sa.Column("source_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.CheckConstraint(
            "batter_runs >= 0 AND extras_runs >= 0 AND total_runs >= 0",
            name=op.f("ck_deliveries_runs"),
        ),
        sa.CheckConstraint(
            "sequence > 0 AND over_number >= 0 AND delivery_number > 0",
            name=op.f("ck_deliveries_order"),
        ),
        sa.CheckConstraint(
            "total_runs = batter_runs + extras_runs", name=op.f("ck_deliveries_run_sum")
        ),
        sa.ForeignKeyConstraint(
            ["batter_id"], ["players.id"], name=op.f("fk_deliveries_batter_id_players")
        ),
        sa.ForeignKeyConstraint(
            ["bowler_id"], ["players.id"], name=op.f("fk_deliveries_bowler_id_players")
        ),
        sa.ForeignKeyConstraint(
            ["innings_id"],
            ["innings.id"],
            name=op.f("fk_deliveries_innings_id_innings"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["non_striker_id"], ["players.id"], name=op.f("fk_deliveries_non_striker_id_players")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_deliveries")),
        sa.UniqueConstraint("innings_id", "sequence", name=op.f("uq_deliveries_innings_id")),
    )
    op.create_index(op.f("ix_deliveries_batter_id"), "deliveries", ["batter_id"], unique=False)
    op.create_index(op.f("ix_deliveries_bowler_id"), "deliveries", ["bowler_id"], unique=False)
    op.create_index(op.f("ix_deliveries_innings_id"), "deliveries", ["innings_id"], unique=False)
    op.create_table(
        "wickets",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("delivery_id", sa.BigInteger(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("player_out_id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("fielders", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["delivery_id"],
            ["deliveries.id"],
            name=op.f("fk_wickets_delivery_id_deliveries"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["player_out_id"], ["players.id"], name=op.f("fk_wickets_player_out_id_players")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_wickets")),
        sa.UniqueConstraint("delivery_id", "ordinal", name=op.f("uq_wickets_delivery_id")),
    )
    op.create_index(op.f("ix_wickets_delivery_id"), "wickets", ["delivery_id"], unique=False)
    op.create_index(op.f("ix_wickets_player_out_id"), "wickets", ["player_out_id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_wickets_player_out_id"), table_name="wickets")
    op.drop_index(op.f("ix_wickets_delivery_id"), table_name="wickets")
    op.drop_table("wickets")
    op.drop_index(op.f("ix_deliveries_innings_id"), table_name="deliveries")
    op.drop_index(op.f("ix_deliveries_bowler_id"), table_name="deliveries")
    op.drop_index(op.f("ix_deliveries_batter_id"), table_name="deliveries")
    op.drop_table("deliveries")
    op.drop_index(op.f("ix_chart_specs_conversation_id"), table_name="chart_specs")
    op.drop_table("chart_specs")
    op.drop_index(op.f("ix_tool_calls_conversation_id"), table_name="tool_calls")
    op.drop_table("tool_calls")
    op.drop_table("match_players")
    op.drop_index(op.f("ix_innings_match_id"), table_name="innings")
    op.drop_table("innings")
    op.drop_index(op.f("ix_external_player_ids_player_id"), table_name="external_player_ids")
    op.drop_table("external_player_ids")
    op.drop_index(op.f("ix_datasets_conversation_id"), table_name="datasets")
    op.drop_table("datasets")
    op.drop_index(op.f("ix_players_name"), table_name="players")
    op.drop_table("players")
    op.drop_index(op.f("ix_messages_conversation_id"), table_name="messages")
    op.drop_table("messages")
    op.drop_index(op.f("ix_matches_format"), table_name="matches")
    op.drop_index(op.f("ix_matches_date_start"), table_name="matches")
    op.drop_table("matches")
    op.drop_table("source_imports")
    op.drop_index(op.f("ix_conversations_owner_id"), table_name="conversations")
    op.drop_table("conversations")
    # ### end Alembic commands ###
